In [43]:
import os
import pandas as pd

In [4]:
'''
Each row contains the catch_id that links to the images.
Also contained in those rows are the user-defined species_ids
as well as the longitude and latitude of the catch.
'''
catchData = pd.read_csv("../fishdata/Fishackathon_CatchData.csv")
'''
Row for each catch_id.
Each row contains the catch_id that links to the images.
Also contained in those rows are the user-defined species_ids as well as the longitude and latitude of the catch.
'''
speciesData = pd.read_csv("../fishdata/Fishackathon_SpeciesData.csv")

In [8]:
print(catchData)

       catch_id  catch_s_id  catch_latitude  catch_longitude  Unnamed: 4  \
0             2          81       47.688656      -122.260940         NaN
1             6          99       44.601627       -92.538246         NaN
2             8         192       47.684585      -122.336720         NaN
3             9         209       48.760392      -122.423088         NaN
4            12         107       37.594400      -122.146900         NaN
5            15          81       38.148100      -119.775100         NaN
6            16         139       37.080700      -121.049400         NaN
7            17         107       37.298500      -122.077200         NaN
8            23         218       47.351500      -121.301700         NaN
9            24         192       47.639900      -122.331200         NaN
10           30          81       42.094100       -84.298500         NaN
11           31         108       29.558300       -95.035900         NaN
12           32          81             NaN              NaN         NaN
13           33          81             NaN              NaN         NaN
14           34         127             NaN              NaN         NaN
15           35          81       47.695000      -122.268700         NaN
16           39          81             NaN              NaN         NaN
17           41          32             NaN              NaN         NaN
18           44          81             NaN              NaN         NaN
19           46         166       46.052502       -95.345947         NaN
20           47         209       45.410627       -94.546191         NaN
21           48          52       44.785297       -93.581775         NaN
22           49          91             NaN              NaN         NaN
23           50         111       33.351100       -80.113400         NaN
24           56         127       46.410500       -94.783900         NaN
25           58         241       49.777025      -112.146638         NaN
26           59         152       49.777261      -112.146507         NaN
27           60         152       49.777310      -112.146678         NaN
28           61          91       49.777261      -112.146507         NaN
29           62         152       49.777261      -112.146507         NaN
...         ...         ...             ...              ...         ...
11632     37808          81       37.470300       -98.082300         NaN
11633     37809         139       38.741900      -121.159100         NaN
11634     37810         127       42.110601       -71.713956         NaN
11635     37816         107       40.401100      -110.322200         NaN
11636     37821          81       33.143000       -97.162000         NaN
11637     37822          81       44.500200       -90.000400         NaN
11638     37823          81       38.784860       -90.250984         NaN
11639     37831          29       19.537800      -154.987800         NaN
11640     37832         143       34.978100       -82.080500         NaN
11641     37844          81       40.619400       -74.831400         NaN
11642     37845          81       36.080629       -95.810089         NaN
11643     37846          81       36.080579       -95.810057         NaN
11644     37847         127       38.551100      -122.231700         NaN
11645     37849          81       35.393200       -80.796400         NaN
11646     37855          81       30.303100       -85.537800         NaN
11647     37857          91       44.160033       -94.836220         NaN
11648     37865          32       30.194000       -81.745500         NaN
11649     37880           5       35.341700       -83.203400         NaN
11650     37882          60       39.964900       -76.478900         NaN
11651     37889          81       45.764400       -92.989900         NaN
11652     37890          81       34.073500       -86.704700         NaN
11653     37891          36       47.487000       -53.273300         NaN
11654     37892         209       32.095700       -90.294000         NaN
11655     37894          70       32.197500       -90.545800         NaN
11656     37954          81       40.388900       -78.718300         NaN
11657     37955          81       28.589900       -80.862900         NaN
11658     37959         306       34.036500      -118.688000         NaN
11659     37973          81       29.488600       -95.150300         NaN
11660     37975         127       40.910000       -74.089300         NaN
11661     37978          19       30.248900       -87.665200         NaN

            Unnamed: 5                                         Unnamed: 6  \
0                  NaN                                                NaN
1             catch_id                 ID number to match to image names
2           catch_s_id  Species ID number, match to species codes on s...
3      catch_latitude                                   Latitude of catch
4      catch_longitude                                 Longitude of catch
5                  NaN                                                NaN
6                  NaN                                                NaN
7                  NaN                                                NaN
8                  NaN                                                NaN
9                  NaN                                                NaN
10                 NaN                                                NaN
11                 NaN                                                NaN
12                 NaN                                                NaN
13                 NaN                                                NaN
14                 NaN                                                NaN
15                 NaN                                                NaN
16                 NaN                                                NaN
17                 NaN                                                NaN
18                 NaN                                                NaN
19                 NaN                                                NaN
20                 NaN                                                NaN
21                 NaN                                                NaN
22                 NaN                                                NaN
23                 NaN                                                NaN
24                 NaN                                                NaN
25                 NaN                                                NaN
26                 NaN                                                NaN
27                 NaN                                                NaN
28                 NaN                                                NaN
29                 NaN                                                NaN
...                ...                                                ...
11632              NaN                                                NaN
11633              NaN                                                NaN
11634              NaN                                                NaN
11635              NaN                                                NaN
11636              NaN                                                NaN
11637              NaN                                                NaN
11638              NaN                                                NaN
11639              NaN                                                NaN
11640              NaN                                                NaN
11641              NaN                                                NaN
11642              NaN                                                NaN
11643              NaN                                                NaN
11644              NaN                                                NaN
11645              NaN                                                NaN
11646              NaN                                                NaN
11647              NaN                                                NaN
11648              NaN                                                NaN
11649              NaN                                                NaN
11650              NaN                                                NaN
11651              NaN                                                NaN
11652              NaN                                                NaN
11653              NaN                                                NaN
11654              NaN                                                NaN
11655              NaN                                                NaN
11656              NaN                                                NaN
11657              NaN                                                NaN
11658              NaN                                                NaN
11659              NaN                                                NaN
11660              NaN                                                NaN
11661              NaN                                                NaN

       Unnamed: 7  Unnamed: 8  Unnamed: 9 Unnamed: 10
0             NaN         NaN         NaN         NaN
1             NaN         NaN         NaN         NaN
2             NaN         NaN         NaN         NaN
3             NaN         NaN         NaN         NaN
4             NaN         NaN         NaN         NaN
5             NaN         NaN         NaN         NaN
6             NaN         NaN         NaN         NaN
7             NaN         NaN         NaN         NaN
8             NaN         NaN         NaN         NaN
9             NaN         NaN         NaN         NaN
10            NaN         NaN         NaN         NaN
11            NaN         NaN         NaN         NaN
12            NaN         NaN         NaN         NaN
13            NaN         NaN         NaN         NaN
14            NaN         NaN         NaN         NaN
15            NaN         NaN         NaN         NaN
16            NaN         NaN         NaN           `
17            NaN         NaN         NaN         NaN
18            NaN         NaN         NaN         NaN
19            NaN         NaN         NaN         NaN
20            NaN         NaN         NaN         NaN
21            NaN         NaN         NaN         NaN
22            NaN         NaN         NaN         NaN
23            NaN         NaN         NaN         NaN
24            NaN         NaN         NaN         NaN
25            NaN         NaN         NaN         NaN
26            NaN         NaN         NaN         NaN
27            NaN         NaN         NaN         NaN
28            NaN         NaN         NaN         NaN
29            NaN         NaN         NaN         NaN
...           ...         ...         ...         ...
11632         NaN         NaN         NaN         NaN
11633         NaN         NaN         NaN         NaN
11634         NaN         NaN         NaN         NaN
11635         NaN         NaN         NaN         NaN
11636         NaN         NaN         NaN         NaN
11637         NaN         NaN         NaN         NaN
11638         NaN         NaN         NaN         NaN
11639         NaN         NaN         NaN         NaN
11640         NaN         NaN         NaN         NaN
11641         NaN         NaN         NaN         NaN
11642         NaN         NaN         NaN         NaN
11643         NaN         NaN         NaN         NaN
11644         NaN         NaN         NaN         NaN
11645         NaN         NaN         NaN         NaN
11646         NaN         NaN         NaN         NaN
11647         NaN         NaN         NaN         NaN
11648         NaN         NaN         NaN         NaN
11649         NaN         NaN         NaN         NaN
11650         NaN         NaN         NaN         NaN
11651         NaN         NaN         NaN         NaN
11652         NaN         NaN         NaN         NaN
11653         NaN         NaN         NaN         NaN
11654         NaN         NaN         NaN         NaN
11655         NaN         NaN         NaN         NaN
11656         NaN         NaN         NaN         NaN
11657         NaN         NaN         NaN         NaN
11658         NaN         NaN         NaN         NaN
11659         NaN         NaN         NaN         NaN
11660         NaN         NaN         NaN         NaN
11661         NaN         NaN         NaN         NaN

[11662 rows x 11 columns]

In [69]:
print(speciesData)

     s_id                    s_name
0       1             Alligator Gar
1       2               Almaco Jack
2       3              American Eel
3       4             American Shad
4       5              Apache Trout
5       6               Arctic Char
6       7           Arctic Grayling
7       8           Atlantic Bonito
8       9              Atlantic Cod
9      10          Atlantic Croaker
10     11          Atlantic Halibut
11     12           Atlantic Salmon
12     13        Atlantic Spadefish
13     14           Bigeye Trevally
14     15               Bigeye Tuna
15     16          Bigmouth Buffalo
16     17            Black Bullhead
17     18             Black Crappie
18     19                Black Drum
19     20             Black Grouper
20     21              Black Marlin
21     22            Black Sea Bass
22     23            Black Skipjack
23     24             Blackfin Tuna
24     25            Blacktip Shark
25     26              Blue Catfish
26     27               Blue Marlin
27     28                Blue Shark
28     29          Bluefin Trevally
29     30              Bluefin Tuna
..    ...                       ...
242   266             Black Buffalo
243   267                Gila Trout
244   269  Lahontan Cutthroat Trout
245   270             Cuttbow Trout
246   272          Hardhead Catfish
247   274                   Panfish
248   275      Bear River Cutthroat
249   276                Don't know
250   277               Calico Bass
251   278            Kokanee Salmon
252   280              Peacock Bass
253   281       Greenback Cutthroat
254   282         Largescale Sucker
255   283            Speckled Trout
256   286                   Sunfish
257   288     Kentucky Spotted Bass
258   290              White Sucker
259   291        Northern Snakehead
260   293                  Tilefish
261   294           Longear Sunfish
262   297              Common Snook
263   299                     Cisco
264   300         Southern Flounder
265   302                  Goldfish
266   306                 Surfperch
267   307           Oyster Toadfish
268   310          Northern Sunfish
269   314           Broad Whitefish
270   316         Atlantic Sturgeon
271   317       Hybrid Striped Bass

[272 rows x 2 columns]

In [85]:
a = catchData.loc[catchData["catch_id"] == 2]
print(a["catch_s_id"].item())

81

In [116]:
## Initialize species id to species name map
idToSpecies = {}
# s_id => s_name
for index, row in speciesData.iterrows():
    idToSpecies[row["s_id"]] = row["s_name"]

In [93]:
## Create directories for each species if they don't exist
PhotosBySpeciesDir = "../fishdata/PhotosBySpecies"
for speciesName in idToSpecies.values():
    os.mkdir(PhotosBySpeciesDir + "/" + speciesName)

{1: 'Alligator Gar', 2: 'Almaco Jack', 3: 'American Eel', 4: 'American Shad', 5: 'Apache Trout', 6: 'Arctic Char', 7: 'Arctic Grayling', 8: 'Atlantic Bonito', 9: 'Atlantic Cod', 10: 'Atlantic Croaker', 11: 'Atlantic Halibut', 12: 'Atlantic Salmon', 13: 'Atlantic Spadefish', 14: 'Bigeye Trevally', 15: 'Bigeye Tuna', 16: 'Bigmouth Buffalo', 17: 'Black Bullhead', 18: 'Black Crappie', 19: 'Black Drum', 20: 'Black Grouper', 21: 'Black Marlin', 22: 'Black Sea Bass', 23: 'Black Skipjack', 24: 'Blackfin Tuna', 25: 'Blacktip Shark', 26: 'Blue Catfish', 27: 'Blue Marlin', 28: 'Blue Shark', 29: 'Bluefin Trevally', 30: 'Bluefin Tuna', 31: 'Bluefish', 32: 'Bluegill', 33: 'Bonefish', 34: 'Bonnethead Shark', 35: 'Bowfin', 36: 'Brook Trout', 37: 'Broomtail Grouper', 38: 'Brown Bullhead', 39: 'Brown Trout', 40: 'Bull Trout', 41: 'Burbot', 42: 'Butterfly Peacock Bass', 43: 'California Corbina', 44: 'California Halibut', 45: 'California Yellowtail', 46: 'Cero Mackerel', 47: 'Chain Pickerel', 48: 'Channel Catfish', 49: 'Chum Salmon', 50: 'Cobia', 51: 'Coho Salmon', 52: 'Common Carp', 53: 'Conger', 54: 'Crevalle Jack', 55: 'Cubera Snapper', 56: 'Cutthroat Trout', 57: 'Dogtooth Tuna', 58: 'Dolly Varden', 59: 'Dolphinfish', 60: 'Flathead Catfish', 61: 'Florida Gar', 62: 'Flounder', 63: 'Freshwater Drum', 64: 'Gag Grouper', 65: 'Giant Trevally', 66: 'Golden Trout', 67: 'Grass Carp', 68: 'Great Barracuda', 69: 'Greater Amberjack', 70: 'Green Sunfish', 71: 'Hammerhead Shark', 72: 'Hogfish', 73: 'Horse-eye Jack', 74: 'Inconnu', 75: 'Kelp Bass', 76: 'King Mackerel', 78: 'Ladyfish', 79: 'Lake Trout', 80: 'Lake Whitefish', 81: 'Largemouth Bass', 82: 'Lingcod', 83: 'Little Tunny', 84: 'Longbill Spearfish', 85: 'Longnose Gar', 86: 'Mako Shark', 87: 'Mangrove Snapper', 88: 'Mountain Whitefish', 89: 'Muskellunge', 90: 'Mutton Snapper', 91: 'Northern Pike', 92: 'Northern Pikeminnow', 93: 'Oscar', 94: 'Pacific Bonito', 95: 'Pacific Cod', 96: 'Pacific Crevalle Jack', 97: 'Pacific Halibut', 98: 'Pacific Sierra Mackerel', 99: 'Paddlefish', 100: 'Permit', 101: 'Pink Salmon', 102: 'Pollock', 103: 'Pompano', 104: 'Porbeagle Shark', 105: 'Pumpkinseed Sunfish', 106: 'Rainbow Runner', 107: 'Rainbow Trout', 108: 'Red Drum', 109: 'Red Grouper', 110: 'Red Snapper', 111: 'Redbreast Sunfish', 112: 'Redear Sunfish', 113: 'Redeye Bass', 114: 'Rock Bass', 115: 'Round Whitefish', 116: 'Sailfish', 117: 'Sauger', 118: 'Saugeye', 119: 'Scamp Grouper', 120: 'Sheepshead', 121: 'Shoal Bass', 122: 'Shortbill Spearfish', 123: 'Shorthead Redhorse', 124: 'Shortnose Gar', 125: 'Silver Redhorse', 126: 'Skipjack Tuna', 127: 'Smallmouth Bass', 128: 'Smallmouth Buffalo', 129: 'Snook', 130: 'Sockeye Salmon', 131: 'Spanish Mackerel', 132: 'Speckled Peacock Bass', 133: 'Splake', 134: 'Spot', 135: 'Spotted Bass', 136: 'Spotted Gar', 137: 'Spotted Seatrout', 138: 'Steelhead', 139: 'Striped Bass', 140: 'Striped Marlin', 141: 'Sturgeon', 142: 'Swordfish', 143: 'Tarpon', 144: 'Tautog', 145: 'Thresher Shark', 146: 'Tiger Muskellunge', 147: 'Tiger Shark', 148: 'Tiger Trout', 149: 'Tope Shark', 150: 'Tripletail', 151: 'Wahoo', 152: 'Walleye', 153: 'Warmouth', 154: 'Weakfish', 155: 'Whalers Shark', 156: 'White Bass', 157: 'White Catfish', 158: 'White Marlin', 159: 'White Perch', 160: 'White Seabass', 161: 'White Shark', 162: 'Whiterock Bass', 164: 'Yellow Bass', 165: 'Yellow Bullhead', 166: 'Yellow Perch', 167: 'Yelloweye Rockfish', 168: 'Yellowfin Tuna', 169: 'Yellowtail Snapper', 170: 'African Pompano', 171: 'Albacore', 172: 'BallanWrasse', 173: 'Barbel', 174: 'Black Sea Bream', 175: 'Bleak', 176: 'Blonde Ray', 178: 'Bream', 179: 'Brill', 180: 'Bull Huss', 181: 'Chub', 182: 'Coalfish', 183: 'Conger eel', 184: 'Dab', 185: 'Dover Sole', 186: 'Eagle Ray', 187: 'Eel', 188: 'Grayling', 189: 'Gudgeon', 190: 'Ling', 192: 'Perch', 193: 'Plaice', 194: 'Pollack', 195: "Ray's Bream", 196: 'Red Bream', 197: 'Roach', 198: 'Rudd', 199: 'Ruffle', 200: 'Silver Bream', 201: 'Smooth Hound', 202: 'Solenette', 203: 'Spurdog', 204: 'Tench', 205: 'Tope', 206: 'Turbot', 207: 'Wels Catfish', 208: 'Zander', 209: 'White Crappie', 210: 'Roanoke Bass', 212: 'Westslope Cutthroat Trout', 213: 'Suwannee Bass', 214: 'Choctaw Bass', 215: 'Colorado River Cutthroat Trout', 216: 'Pallid Sturgeon', 220: 'Palmetto Bass', 221: 'Orange Spotted Sunfish', 222: 'Chinook Salmon', 223: 'White Sturgeon', 224: 'Humpback Whitefish', 228: 'Green Sturgeon', 229: 'Summer Flounder', 232: 'Arctic Cisco', 233: 'Starry Flounder', 234: 'Bonito', 237: 'Redband Trout', 238: 'Dolly Varden Trout', 240: 'Tilapia', 242: 'Shovelnose Sturgeon', 243: 'Lake Sturgeon', 244: 'Blue Sucker', 245: 'Fallfish', 247: 'Croaker', 249: 'Peamouth', 250: 'Palomino Trout', 251: 'Snake River Cutthroat Trout', 253: 'Cusk', 257: 'Mackerel', 258: 'Pigfish', 259: 'Utah Sucker', 260: 'Guadalupe Bass', 261: 'Coastal Cutthroat', 262: 'Grass Pickerel', 263: 'Spotted Sunfish', 264: 'Least Cisco', 265: 'Sacramento Perch', 266: 'Black Buffalo', 267: 'Gila Trout', 269: 'Lahontan Cutthroat Trout', 270: 'Cuttbow Trout', 272: 'Hardhead Catfish', 274: 'Panfish', 275: 'Bear River Cutthroat', 276: "Don't know", 277: 'Calico Bass', 278: 'Kokanee Salmon', 280: 'Peacock Bass', 281: 'Greenback Cutthroat', 282: 'Largescale Sucker', 283: 'Speckled Trout', 286: 'Sunfish', 288: 'Kentucky Spotted Bass', 290: 'White Sucker', 291: 'Northern Snakehead', 293: 'Tilefish', 294: 'Longear Sunfish', 297: 'Common Snook', 299: 'Cisco', 300: 'Southern Flounder', 302: 'Goldfish', 306: 'Surfperch', 307: 'Oyster Toadfish', 310: 'Northern Sunfish', 314: 'Broad Whitefish', 316: 'Atlantic Sturgeon', 317: 'Hybrid Striped Bass'}

In [158]:
'''
Associate photos with species tag
'''
'''
Each image within that file has a filename that consists of ####_#######_#.png.
The first set of numbers is the most important to you.
Those are the numbers that will link that image to the data contained in the .CSV file
Those first numbers are the catch_id numbers and are the unique identifiers for each catch logged in NetFish.
'''
AllPhotosPath = "../fishdata/AllPhotos"
PhotosBySpeciesDir = "../fishdata/PhotosBySpecies"

speciesDict = {}
for subdir, dirs, files in os.walk(AllPhotosPath):
    for file in files:
        if (file[-4:] == ".jpg"):
            # translate file's catch_id to species_id
            catch_id = file.split("_")[0]
            species_row = catchData.loc[catchData["catch_id"] == int(catch_id)]
            #print(species_row)
            species_id = (species_row["catch_s_id"])
            species_id = species_id.asobject
            if (len(species_id) == 0):
                continue
            species_id = species_id[0]
            #print(idToSpecies[species_id])
            #print(PhotosBySpeciesDir + "/" + idToSpecies[species_id] + "/" + file)
            if (species_id in idToSpecies):
                #print(PhotosBySpeciesDir + "/" + idToSpecies[species_id] + "/" + file)
                os.rename(subdir + "/" + file, PhotosBySpeciesDir + "/" + idToSpecies[species_id] + "/" + file)

In [166]:
count = 0
for subdir, dirs, files in os.walk(PhotosBySpeciesDir):
    count += (len(files))
print(count)

12022

In [162]:
# Sanity check, get counts for each species
speciesCounts = {}

PhotosBySpeciesDir = "../fishdata/PhotosBySpecies"
for val in idToSpecies.values():
    speciesCounts[val] = 0
for subdir, dirs, files in os.walk(PhotosBySpeciesDir):
    for file in files:
        if (file[-4:] == ".jpg"):
            catch_id = file.split("_")[0]
            species_row = catchData.loc[catchData["catch_id"] == int(catch_id)]
            #print(species_row)
            species_id = (species_row["catch_s_id"])
            species_id = species_id.asobject
            if (len(species_id) == 0):
                continue
            species_id = species_id[0]
            speciesCounts[idToSpecies[species_id]] += 1
            
for key in speciesCounts:
    print("{} : {}".format(key, speciesCounts[key]))

Alligator Gar : 59
Almaco Jack : 0
American Eel : 17
American Shad : 3
Apache Trout : 15
Arctic Char : 0
Arctic Grayling : 1
Atlantic Bonito : 0
Atlantic Cod : 2
Atlantic Croaker : 5
Atlantic Halibut : 0
Atlantic Salmon : 1
Atlantic Spadefish : 3
Bigeye Trevally : 0
Bigeye Tuna : 0
Bigmouth Buffalo : 5
Black Bullhead : 25
Black Crappie : 220
Black Drum : 35
Black Grouper : 0
Black Marlin : 1
Black Sea Bass : 13
Black Skipjack : 2
Blackfin Tuna : 2
Blacktip Shark : 14
Blue Catfish : 201
Blue Marlin : 1
Blue Shark : 3
Bluefin Trevally : 2
Bluefin Tuna : 2
Bluefish : 31
Bluegill : 411
Bonefish : 1
Bonnethead Shark : 12
Bowfin : 49
Brook Trout : 9
Broomtail Grouper : 0
Brown Bullhead : 14
Brown Trout : 28
Bull Trout : 15
Burbot : 0
Butterfly Peacock Bass : 25
California Corbina : 2
California Halibut : 5
California Yellowtail : 5
Cero Mackerel : 0
Chain Pickerel : 85
Channel Catfish : 557
Chum Salmon : 0
Cobia : 3
Coho Salmon : 16
Common Carp : 231
Conger : 0
Crevalle Jack : 13
Cubera Snapper : 0
Cutthroat Trout : 0
Dogtooth Tuna : 2
Dolly Varden : 0
Dolphinfish : 15
Flathead Catfish : 121
Florida Gar : 2
Flounder : 25
Freshwater Drum : 54
Gag Grouper : 6
Giant Trevally : 3
Golden Trout : 8
Grass Carp : 48
Great Barracuda : 9
Greater Amberjack : 2
Green Sunfish : 89
Hammerhead Shark : 1
Hogfish : 1
Horse-eye Jack : 1
Inconnu : 0
Kelp Bass : 2
King Mackerel : 13
Ladyfish : 7
Lake Trout : 32
Lake Whitefish : 2
Largemouth Bass : 6193
Lingcod : 6
Little Tunny : 6
Longbill Spearfish : 0
Longnose Gar : 26
Mako Shark : 0
Mangrove Snapper : 8
Mountain Whitefish : 0
Muskellunge : 55
Mutton Snapper : 3
Northern Pike : 405
Northern Pikeminnow : 7
Oscar : 1
Pacific Bonito : 1
Pacific Cod : 0
Pacific Crevalle Jack : 1
Pacific Halibut : 8
Pacific Sierra Mackerel : 0
Paddlefish : 24
Permit : 2
Pink Salmon : 3
Pollock : 0
Pompano : 3
Porbeagle Shark : 2
Pumpkinseed Sunfish : 52
Rainbow Runner : 0
Rainbow Trout : 346
Red Drum : 99
Red Grouper : 1
Red Snapper : 10
Redbreast Sunfish : 13
Redear Sunfish : 27
Redeye Bass : 6
Rock Bass : 55
Round Whitefish : 1
Sailfish : 1
Sauger : 15
Saugeye : 8
Scamp Grouper : 0
Sheepshead : 12
Shoal Bass : 5
Shortbill Spearfish : 0
Shorthead Redhorse : 2
Shortnose Gar : 6
Silver Redhorse : 1
Skipjack Tuna : 1
Smallmouth Bass : 828
Smallmouth Buffalo : 16
Snook : 18
Sockeye Salmon : 0
Spanish Mackerel : 9
Speckled Peacock Bass : 2
Splake : 0
Spot : 0
Spotted Bass : 118
Spotted Gar : 21
Spotted Seatrout : 31
Steelhead : 4
Striped Bass : 220
Striped Marlin : 1
Sturgeon : 3
Swordfish : 0
Tarpon : 7
Tautog : 5
Thresher Shark : 0
Tiger Muskellunge : 25
Tiger Shark : 3
Tiger Trout : 3
Tope Shark : 0
Tripletail : 0
Wahoo : 4
Walleye : 268
Warmouth : 19
Weakfish : 2
Whalers Shark : 0
White Bass : 42
White Catfish : 15
White Marlin : 1
White Perch : 4
White Seabass : 0
White Shark : 0
Whiterock Bass : 1
Yellow Bass : 7
Yellow Bullhead : 19
Yellow Perch : 60
Yelloweye Rockfish : 5
Yellowfin Tuna : 9
Yellowtail Snapper : 3
African Pompano : 0
Albacore : 1
BallanWrasse : 0
Barbel : 0
Black Sea Bream : 1
Bleak : 2
Blonde Ray : 5
Bream : 16
Brill : 0
Bull Huss : 1
Chub : 18
Coalfish : 0
Conger eel : 0
Dab : 0
Dover Sole : 0
Eagle Ray : 3
Eel : 1
Grayling : 0
Gudgeon : 0
Ling : 0
Perch : 76
Plaice : 0
Pollack : 0
Ray's Bream : 0
Red Bream : 0
Roach : 4
Rudd : 1
Ruffle : 0
Silver Bream : 1
Smooth Hound : 3
Solenette : 0
Spurdog : 1
Tench : 1
Tope : 1
Turbot : 0
Wels Catfish : 0
Zander : 0
White Crappie : 112
Roanoke Bass : 0
Westslope Cutthroat Trout : 1
Suwannee Bass : 7
Choctaw Bass : 6
Colorado River Cutthroat Trout : 4
Pallid Sturgeon : 0
Palmetto Bass : 0
Orange Spotted Sunfish : 1
Chinook Salmon : 5
White Sturgeon : 12
Humpback Whitefish : 4
Green Sturgeon : 12
Summer Flounder : 1
Arctic Cisco : 0
Starry Flounder : 2
Bonito : 5
Redband Trout : 26
Dolly Varden Trout : 17
Tilapia : 6
Shovelnose Sturgeon : 2
Lake Sturgeon : 0
Blue Sucker : 10
Fallfish : 3
Croaker : 1
Peamouth : 1
Palomino Trout : 1
Snake River Cutthroat Trout : 1
Cusk : 34
Mackerel : 0
Pigfish : 1
Utah Sucker : 0
Guadalupe Bass : 3
Coastal Cutthroat : 1
Grass Pickerel : 3
Spotted Sunfish : 17
Least Cisco : 0
Sacramento Perch : 0
Black Buffalo : 12
Gila Trout : 34
Lahontan Cutthroat Trout : 1
Cuttbow Trout : 25
Hardhead Catfish : 1
Panfish : 8
Bear River Cutthroat : 7
Don't know : 0
Calico Bass : 0
Kokanee Salmon : 1
Peacock Bass : 4
Greenback Cutthroat : 0
Largescale Sucker : 0
Speckled Trout : 8
Sunfish : 5
Kentucky Spotted Bass : 1
White Sucker : 1
Northern Snakehead : 0
Tilefish : 0
Longear Sunfish : 1
Common Snook : 9
Cisco : 0
Southern Flounder : 2
Goldfish : 1
Surfperch : 2
Oyster Toadfish : 0
Northern Sunfish : 0
Broad Whitefish : 0
Atlantic Sturgeon : 0
Hybrid Striped Bass : 4

In [163]:
print(sum(speciesCounts.values()))

12337

In [167]:
import requests

In [176]:
r = requests.get("http://www.fishbase.org/ComNames/CommonNameSearchList.php")
print("status: {}".format(r.status_code))
print("text: {}".format(r.text))

status: 200
json:

No exact match was found for <b>''</b>. <br/> Please wait. Searching for the near match of your input among <b> thousands of data </b>.<br/> This may take a minute or so.<meta HTTP-EQUIV='refresh' content=0;url='../NoRecordForCommonName.php?crit1_operator=EQUAL&CommonName='>